GoogleChrome/rendertron

package.json
src/renderer.js
test/app-test.js
test/resources/inject-element.js
test/resources/script-after-load.html
yarn.lock

Using a [virtual time budget](https://docs.google.com/document/d/1y9KDT_ZEzT7pBeY6uzVt1dgKlwc1OB_vY4NZO1zBQmo/edit#heading=h.tn3gd1y9ifml) makes the rendering deterministic. This change updates the loading function to use a virtual time budget, which allocates a maximum allowed time spent in scripts & rendering. This function ensures the `pageload` event has fired, and all network requests have completed.
This change also updates the resulting dump to including the full HTML of the page, not just the `head` element.

Deterministic rendering function

---

README.md
src/main.js
src/renderer.js
test/app-test.js
test/cache-test.js
test/resources/http-meta-status-code-multiple.html
test/resources/http-meta-status-code.html

Forward status codes and allow it to be set via custom meta tag

---

Dockerfile
package.json
src/main.js
yarn.lock

See https://github.com/GoogleChrome/lighthouse/blob/master/chrome-launcher/chrome-launcher.ts#L187

Don't use portscanner, use chrome-launcher's random port finder

---

README.md
src/main.js
src/renderer.js
test/app-test.js

Add screenshot endpoint

---

src/main.js
test/cache-test.js

Closes #39 as invalid issue with test verifying this.

Update cache endpoints & add extra cache test

---

src/index.html
src/main.js

* Screenshot always uses current window dimensions so image fits exactly.
* Focus ring on all the items.

Add homepage

---

src/renderer.js

Fixes #40.
Prior to this change, the `stripPage()` function was called. When combined with `link rel='import'` and scoped style (without shady DOM/CSS enabled), screenshots would appear different from expected.
This change moves the `stripPage()` function call to just the `render` endpoint. This also uses mobile emulation, which allows for viewport meta tag, overlay scrollbars, text autosizing. See [the docs](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride) for more details on the implications of mobile emulation.

Screenshots use mobile emulation and don't strip page using it

---

src/index.html

* Add view docs button
* Tweak font sizes, other styles

Home page updates

---

README.md
src/renderer.js

Set a hard 10 second time limit

---

README.md
src/main.js
test/app-test.js

Allow render domains to be restricted

---

README.md
bower.json
package.json
src/index.html
src/main.js
yarn.lock

Move bower dep over to NPM

---

middleware/src/middleware.js
middleware/test/middleware-test.js
src/cache.js
src/index.html
src/main.js
src/renderer.js
test/app-test.js
test/cache-test.js
test/resources/basic-script.html
test/resources/custom-element.html
test/resources/explicit-render-event.html
test/resources/http-meta-status-code-multiple.html
test/resources/http-meta-status-code.html
test/resources/include-script.html
test/resources/inject-element-after-load.js
test/resources/inject-element.js
test/resources/script-after-load.html
test/resources/shadow-dom-no-polyfill.html
test/resources/shadow-dom-polyfill-all.html
test/resources/shadow-dom-polyfill-loader.html

copyright headers

---

src/main.js
test/app-test.js

Fix thrown exception on unknown URL for screenshots

---

src/index.html

Current behaviour: When URL is empty it doesn't indicate any error.
Changes made: Change border color when an empty URL is given.
Change done in:
- [src/index.html](https://github.com/GoogleChrome/rendertron/blob/master/src/index.html)

Change border color on empty URL

---

README.md

Update readme to clarify CentOS issue

---

src/renderer.js

It appears the use of virtual time budget set to `pauseIfNetworkFetchesPending` results in pages being unable to load. This changes the loading function to determine loading as follows:
* Page load event has fired
* Network has been completely idle for 500ms
* A virtual time budget of 5 seconds allows renderer to advance ahead of real time. This budget is triggered only after the above two conditions have been met.
* Maximum allowed budget of 10 seconds

Remove use of virtual time budget as blocker

---

src/renderer.js

Allow service workers to be used

---

package.json
src/renderer.js
yarn.lock

Fix timeout

---

README.md
src/renderer.js
test/resources/explicit-render-event.html

Support an explicit render flag instead of an event

---

README.md
bin/rendertron
package.json

* Published to NPM.
* Added `rendertron` CLI.

Publish to NPM and add a CLI

---

CHANGELOG.md
README.md
src/main.js

Log requested render URLs when using debug

---

README.md

Add ASP.net middleware to the readme

---

package-lock.json
package.json

Closes #143.
semver package is required in the CLI script.

Add missing semver dep

---

src/main.js
src/renderer.js

Fix debug mode

---

package-lock.json
package.json

`np` was unable to push this change since all changes must be reviewed.

Update package version to 1.1.1

---

src/index.html

Fix URLs with # fragments

---

middleware/CHANGELOG.md
middleware/package-lock.json
middleware/package.json

Prepare rendertron-middleware 0.1.5 release

---

README.md

Update README to say datastoreCache in config

---

package-lock.json
package.json
src/rendertron.ts

Updating to TypeScript 3.6.2

---

docs/index.md

#321  Updated the github emojis with image equivalents

Updated the github emojis with image equivalents 

---

docs/configure.md

- Created `docs/configure.md` file and explained the configurations from `readme.md`

fixed issue #324

---

docs/deploy.md

#317 [Docs] documentation on deployment via gcloud.

[Docs] documentation on deployment via gcloud #317

---

README.md
docs/configure.md
src/config.ts
src/rendertron.ts

#264 (how to specify hostname) fixed , added process.env.HOST

added hostname (how to specify hostname #264)

---

CONTRIBUTING.md

In order to help new contributors and give guidance on what we expect from a pull request, we should have a CONTRIBUTING.md file. Github will automatically add a UI element to the PR-submit form that encourages authors to read this guidance before submitting the PR.

Adds a CONTRIBUTING.md

---

docs/server-setup.md

Added the server setup docs
- How to use rendertron-middleware for node.js webservers
- How to set up Apache or Nginx

Added the server setup docs

---

docs/deploy.md

heroku steps added

---

docs/index.md

Adds a link to a new doc that should discuss server setups

Add server-setup to docs

---

docs/api-reference.md
docs/index.md
package-lock.json

Fixes #340

---

README.md
src/datastore-cache.ts
src/memory-cache.ts
src/test/datastore-cache-test.ts
src/test/memory-cache-test.ts

Fixes #343 
Comments please! Thanks!

Add refreshCache parameter to render API

---

src/rendertron.ts

Auto create browser when disconnected

---

middleware/package-lock.json
middleware/package.json
package-lock.json
package.json

* Move `@types/fs-extra` and `@types/express` to dev dependencies.
* Remove unused `uuid` dependency.
* Update dependencies.

Clean dependencies

---

src/renderer.ts
src/test/app-test.ts
test-resources/include-doctype.html

Hi @AVGP , 
This is my fix for #378 
Can you take a look? Thanks!

Include doctype in render output

---

docs/server-setup.md

I've fixed the broken code block.

add code block of server-setup.md

---

package.json
src/index.html

Hi there,
I reimplemented a loading/progress bar as mentioned in #360 and removed the now unused dependency `progress-bar-element` from package.json.

Implemented loading bar

---

README.md
src/config.ts
src/filesystem-cache.ts
src/rendertron.ts
src/test/filesystem-cache-test.ts

This is my attempt at https://github.com/GoogleChrome/rendertron/issues/338

add filesystem cache

---

src/test/datastore-cache-test.ts
src/test/filesystem-cache-test.ts
src/test/memory-cache-test.ts

Fix intermittent refreshCache refreshes cache test

---

src/rendertron.ts

Hi there,
This should fix #385

Fixed error with host and port in config.js

---

src/renderer.ts
src/test/app-test.ts

Adds a test for #361 and resolves a glitch when the rendered URL includes the file name.

Adds test for base href, fixes subfolder href

---

src/renderer.ts
test-resources/include-script.html
test-resources/inject-element-module.js

fix: strip module scripts #406

---

CHANGELOG.md

After bumping the version number in the main branch, for the Changelog I shall follow procedure again 😁

Landing 3.0.0

---

src/renderer.ts

Hello,
I’m a security researcher at [r2c](https://r2c.dev (https://r2c.dev/)). We work with industry experts to write code checks for bugs in open source.
Problem:
Requests to the Google Cloud metadata endpoints (e.g http://metadata.google.internal/computeMetadata/v1beta1/instance/service-accounts/default/token) are restricted in the recent version of Rendertron (https://github.com/GoogleChrome/rendertron/commit/8aeeda7765101b705d5c8c2801ec81c1d43df40e) but those restrictions can be bypassed if the request is sent inside an iFrame. Thus, an attacker who has access to the '/screenshot' endpoint of Rendertron can exfiltrate Google Cloud metadata.
Fix:
With current PR I try to restrict requests from the loaded page to the `.internal` endpoints (including iFrames)
I do not provide unit tests …

Update renderer to restrict requests to .internal endpoints

---

README.md
docs/configure.md
src/config.ts
src/rendertron.ts
src/test/app-test.ts

Implementing whitelisting functionality from v1.1.0

Add url whitelisting support

---

.github/workflows/main.yml

Travis has been very slow recently and there's been an ongoing question if this repository can continue to use Travis anyway, so I set up Github Actions to replace Travis.

Adds Github action to replace travis

---

docs/api-reference.md

Hey @AVGP, I am not sure if I did everything right. Please let me know if I need to change anything.

Add health check URL to API docs resolves #595
