Dockerfile
README.md
chromium.js

This patch does a few things:
1. Moves to Chrome Stable (since headless is now in 59).
2. Reduces the layer count in the docker file build.
3. Fixes lint errors in Dockerfile
4. Adds a non-privileged user called `botrender` to container (so you don't have to use `--unsafe-perm` with the npm install)
5. Expose 8080 for port binding and add documentation to allow running against service without `docker exec`
6. Document seccomp and SYS_ADMIN flags to reduce ECONNREFUSED confusion and use of `--disable-sandbox` as noted in #3

Chrome Stable + Docker lints

---

.travis.yml
package.json
src/cache.js
src/main.js
src/renderer.js
test/cache-test.js
yarn.lock

Part of #5.
This change adds a basic caching layer which uses the Google Cloud Datastore to store cached content to serve. Summary rationale for choosing datastore over a memcached solution like redis is that this caching layer is unique in that it is trying to avoid expensive rendering costs instead of sub-ms response times. Datastore retrieval times are slower, but allow us to implement a perfect cache with large storage backing it.

Add a basic, optional cache layer

---

README.md
package.json
src/renderer.js
test/app-test.js

Fixes #18.
Scoping shim is required to properly serialize styles. However, injecting the scoping shim doesn't work since nothing on the document exists yet. As such, this enables the scoping shim but requires `webcomponents-loader.js` to work.

Scoping shim is enabled using loader

---

src/main.js
src/renderer.js

This change allows console messages from the rendered page to be plumbed through to the node console.

Add --debug flag which logs console messages

---

package.json
src/main.js
src/renderer.js
yarn.lock

When running on Google Cloud, instances are automatically scaled. However, because it was always using the default remote debugging port (9222) to talk to Chrome, these instances could block each other from functioning as expected.
This change ensures each instance finds its own available port to use for remote debugging.

Scan ports and use a new port on every instance

---

src/renderer.js

This is a purely cosmetic change. With the base href set, when previewing output from the service, resources like images will be able to resolve to the original server correctly. This doesn't affect the serialised output, except for the addition of the base tag.

Inject <base href> tag into page to allow output to be rendered nicely

---

app.yaml

This will change instance machine types to `n1-standard-8`, which should improve render times.
Reference: https://cloud.google.com/compute/docs/machine-types

Beef up instance capabilities

---

README.md
src/renderer.js

* Screenshots are restricted to 1500*1500 since compression for PNG screenshots is not available. Source: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot
* Animations are sped up to 1000x to alleviate issues where screenshots are taken when the page is loaded but there are still loading animations on screen.
* Fix an exception where budget can end up being a non-integer value.

Restrict screenshot size and speed up animations

---

src/renderer.js

Closes #51.
This change enables the browser cache since the browser respects the caching headers set by servers. As with regular users, its the servers responsibility to set the right caching headers. This improves performance on different pages within the same application.

Enable browser cache

---

Dockerfile
README.md
package.json
src/main.js
src/renderer.js

Closes #36.
Refactor to use config.json instead of command line options.

Load config from config.json

---

middleware/src/middleware.js
middleware/test/middleware-test.js

The query parameter to enable Shady DOM for web components v1 is `wc-inject-shadydom=true`. Without setting to `true` `render-tron` won't work.
This works: http://render-tron.appspot.com/render/https://polymer-shop.appspot.com/?wc-inject-shadydom=true
Fixes https://github.com/GoogleChrome/rendertron/issues/81

Fix middleware to set query parameter to "wc-inject-shadydom=true"

---

.gitignore
src/index.html
src/main.js
src/renderer.js
test/app-test.js

This PR fixes a few issues listed below:
- changes errors to be more generic, removing extraneous information to user
- adds validation for urls to only originate from 'http' or 'https' protocols
- sorts requires by alphabetical (node, node_modules, project) order
- only exposes `/_ah/stop` if `NODE_ENV` is set to `development`
- only exposes `progress-bar.html` used in application

fix: clean errors, add validation & reduce exposed

---

src/index.html

Related to #77 
Changes done in:
- [src/index.html](https://github.com/GoogleChrome/rendertron/blob/master/src/index.html)
This change will append `https` if no protocol is given in the UI.

Use HTTPS when no protocol is provided

---

src/cache.js
src/main.js
test/app-test.js
test/cache-test.js

This change sets 2 additional headers:
- `x-renderer` is set to `rendertron` for all responses served via rendertron.
- `x-rendertron-cached` is set when the response is served from rendertron's cache. Its value is set to the time the cached response was created. Format is per `Date` general header (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Date).

Set response headers to indicate renderer & cache status

---

src/renderer.js

Fixes issues reported in #43. `--headless` doesn't have support for the GPU yet. As a result, in some cases, some buffer is being hit and the resulting screenshot is missing areas. This appears to be caused by a combination of high DPR, large dimensions, complex rendering (eg. images).
Reducing DPR to 1 alleviates this issue but presumably will not fix this issue until headless supports the GPU.

Set device scale ratio to 1

---

Dockerfile

As you know, screenshot function maybe not work well on some web page which contains chinese characters or some others.
So I add Microsoft YaHei fonts to thirdfonts/ fold to support above-mentioned problem.
And anyone could add fonts to thirdfonts/ fold and rebuild docker image to make things work.
I hope you can adopt this ;)

support thirdparty fonts

---

Dockerfile
src/main.js

Closes #111.
See https://github.com/Googlechrome/puppeteer/issues/290 on the same issue.
The `--disable-gpu` flag is no longer required on Linux and Mac OS. See crbug.com/737678 for more details.

Disable sandbox when running headless chrome

---

README.md
src/index.html
src/renderer.ts
src/rendertron.ts

For example, rendering youtube.com as mobile gives the mobile optimised experience:

Add an option to render as mobile

---

src/renderer.ts
src/test/app-test.ts
test-resources/include-json-ld.html

When using [Structured Data](https://developers.google.com/search/docs/guides/intro-structured-data) I noticed that Rendertron by default strips **all** script tags, no matter what they contain. I think it should not strip all script tags, because there might be reasons to have script tags that aren't JavaScript in your sources.
I made my patch a little broader, i.e. it conserves all scripts that aren't JavaScript. It only strips scripts without a `type` attribute or a `type` attribute that contains "javascript". If you think this is too broad, I'd be happy to narrow it down to exclude scripts of the type `application/ld+json` as that's the edge case I care most about.
Let me know what you think!

Do not strip all scripts

---

middleware/src/middleware.ts
package-lock.json

event-stream@3.3.6 was unpublished from NPM [following an incident](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident) so `npm install` currently fails. This fixes that.

Remove event-stream@3.3.6 from package-lock.json

---

src/renderer.ts

This PR fixes possible memory leak when renderer returns early after found an error. The page should be closed before every return to avoid a huge pile of unused pages.

Always close page before return to prevent memory leak

---

src/renderer.ts

This PR fixes a memory leak when rendering page screenshots. `Renderer.screenshot()` doesn't close the page on completion (even if successful), thus leaving renderer processes behind.
Follows along the lines of #268

Close page after screenshot to avoid memory leak

---

README.md

The last few days I've been working on a `python-rendertron` package. I actually was surprised it didn't exist yet! Even tho it's only on version `0.2.0` it is stable. It's set up to be able to integrate support for different frameworks in the future although it's currently [Django](https://djangoproject.com) only.
This pull request adds a link to https://github.com/frontendr/python-rendertron in the same manner as the current list of middlewares.
Kind regards!

Added a link to the python-rendertron package.

---

middleware/README.md

In #160 it becomes clear that the description for the `timeout` option in the middleware is misleading. This should make that clearer.

Adjusts timeout doc for middleware. fixes #160

---

package.json
src/test/datastore-cache-test.ts

* The datastore emulator seems to work differently depending on the version of gcloud utils installed, so we specify the port.
* The datastore cache was flaky due to race conditions with the network operation to the gcloud datastore, so we increase the wait time.
* The `test-cache` task wasn't testing the in-memory cache, so we add it.

Improves cache tests

---

docs/index.md

There are a couple of issues here.
1. The `img` tag is being wrapped in an `a` tag. One way is to set `href` to `#` (which I've done).
2. When using the actual emoji, it is being replaced by an g-emoji element, which has its own styles plus it sets the height and width to '1rem'.
TLDR: The position and size is not absolutely same as the emoji.
Resolves #321

[Docs] Updated emojis

---

app.yaml

Node 8 on App Engine is deprecated. 
Node 12 is the latest version, and should be GA soon.

Update App Engine from Node 8 to Node 12

---

src/renderer.ts

Refere to [Issue 351](https://github.com/GoogleChrome/rendertron/issues/351) for more details.

Bug fix: read timeout from config instead of hard coded value

---

src/config.ts
src/rendertron.ts

Reworked @japboy's pull request to pass through puppeteer args via config.json.
Supersedes #279

Allows specifying puppeteer arguments in config

---

middleware/README.md
middleware/src/middleware.ts
middleware/src/test/middleware-test.ts

See #354 .
Instead of using a callback as proposed in the issue (which is more flexible), I chose to implement by allowing the user to opt in by providing a list of allowed forwarded hosts.
This way users cannot so easily open themselves to a security flaw by not applying an allow-list to the forwarded host header input.

Implement forwarded host functionality

---

.travis.yml
middleware/package-lock.json
middleware/package.json
package.json
src/filesystem-cache.ts

Fix 387: TravisCI is failing

---

docs/index.md

The current landing page of the docs (https://googlechrome.github.io/rendertron/) had a broken link to the contributing documentation. This fixes that link :)

Fixes the link to CONTRIBUTING.md in the docs

---

src/renderer.ts

Base url used as root for relative paths and should contain whole path without query string.
E.g. there is `<link href="styles/widget.css" rel="stylesheet">` on page `https://example.tld/project/`. Relative link will be `https://example.tld/styles/widget.css` but should be `https://example.tld/project/styles/widget.css`
This works even if base url will be `https://example.tld/project/index.html`

Fix base url with using pathname

---

src/filesystem-cache.ts

Re-adds support for "cacheDurationMinutes": -1 as per issue #410

Fixed filesystem "cacheDurationMinutes": -1 issue #410

---

.travis.yml
src/filesystem-cache.ts

The cache tests highlighted a fundamental robustness issue in the filesystem cache.
Only the constructor checks if the directory that the cache uses is present and creates directories if necessary.
When using clearAll, however, the directory is deleted. That's fine, but the next request fails as the cache directory is neither readable nor writable.
This PR fixes the problem by checking the directory on every request, re-creating it if it doesn't.
While this does incurr a bit of a runtime cost for looking up the filesystem, it makes Rendertron more robust against runtime failures when the directory gets deleted, either through `clearAllCache` or outside of the process.

Fixes Filesystem cache

---

src/rendertron.ts
src/test/app-test.ts

This prevents Rendertron from leaking google.internal URLs as those used in AppEngine.

Fixes security issue with AppEngine deployments

---

.travis.yml
src/test/app-test.ts
src/test/memory-cache-test.ts

This PR fixes two failing tests:
- app-test.ts had an outdated config mock
- memory-cache-test.ts had a test case with side effects

Fixes tests

---

README.md
docs/api-reference.md
src/filesystem-cache.ts
src/rendertron.ts
src/test/app-test.ts
src/test/filesystem-cache-test.ts
src/test/memory-cache-test.ts

Addresses #420 
1.  Adds `/invalidate` handler to the filesystem cache
2. `README.md` & `docs/api-reference.md` amended
3. Test added
~~Question on the test, it created a folder in the same dir as the renderton install `./renderton-test-cache` and then removes this after the test has run, is this a legitimate way to do this?~~ changed to use os temp dir in ee7b4ba

Filesystem invalidate endpoint

---

src/renderer.ts

Sites that had a `<base href="/" >` were being rendered with `origin` & `//`  i.e. `<base href="https://example.com//" />`
Adds a check for the base href being only `"/"` and injects just `origin` if so.

fixes <base ref="/" > being changed to origin & double slash

---

src/filesystem-cache.ts

Fixes a bug where the filename to delete was sometime looking for `.json.json` instead of `.json`, should fix the issue reported in #430 
Also adds console.log() error reporting if the file fails to delete.

Filesystem cache bug Fixed, additional logging added

---

src/renderer.ts
src/test/app-test.ts
test-resources/include-base-as-directory.html
test-resources/include-base.html

Hello
I believe there is some inconsistency on the injectBaseHref function.
Let's assume that I have the base url defined as "/".
Then the following will happen when using rendertron:
- https://mywebsite.com -> base = https://mywebsite.com/ -> Ok
- https://mywebsite.com/dir1/page -> base = https://mywebsite.com/ -> Ok
- https://mywebsite.com/dir1/dir2/page -> base = https://mywebsite.com/dir1 -> **NOk**
I believe this is happening because the path.dirname(path) returns the directory of the path. In the last example the directory is /dir1/dir2. But the base url should be https://mywebsite.com/.
Hugo

Remove intermediary directory from base href

---

README.md
package-lock.json
src/config.ts
src/renderer.ts
src/test/app-test.ts
test-resources/request-header.html

Some users need to add some headers, for example, to access the restricted environment.
In my case, we need to add custom header to access the my environment.
- Add `reqHeaders` in config
- Set the above header in puppeteer

feature: add reqHeaders

---

app.json
docs/deploy.md

Test the one click deployment here:
https://dashboard.heroku.com/new?button-url=https://github.com/NNTin/rendertron/tree/main&template=https://github.com/NNTin/rendertron/tree/main
I moved the button into docs/deploy.md. However the Heroku steps listed there are a bit faulty:
> First, add the Google Chrome buildpack to your project:
> 
> `$ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-google-chrome.git -a <app-name>`
> Next, add the heroku/nodejs buildpack to your project:
> 
> ~~`$ heroku buildpacks:add heroku/nodejs -a <app-name>`~~
> `$ heroku buildpacks:add --index 2 heroku/nodejs -a <app-name>`
explanation for `--index 2` follows below. This step is now automated via `app.json`. The buildpacks are automatically added via the Heroku dashboard/website/1-click …

1 click Heroku deployment

---

bin/rendertron

according to `package.json` (https://github.com/GoogleChrome/rendertron/blob/d1bcb13422395264f3f39aa2a1b5ec83438c681e/package.json#L8) Rendertron requires Node.js >= 10 to work, seems to be reasonble to bump its version in bin/rendertron

Update required version of Node in bin/rendertron

---

src/datastore-cache.ts
src/memory-cache.ts

As the Rendertron requires/forces Node.js version >= 10 to be used
https://github.com/GoogleChrome/rendertron/blob/d1bcb13422395264f3f39aa2a1b5ec83438c681e/package.json#L8
https://github.com/GoogleChrome/rendertron/blob/78492cc325a4022f2de27a1bbb0c84806afdd498/bin/rendertron#L9
I would like to propose moving from the deprecated `new Buffer(...)` to `Buffer.from(...)`
https://nodejs.org/dist/latest-v12.x/docs/api/buffer.html#buffer_static_method_buffer_from_array

Update new Buffer(...) to Buffer.from(...)

---

README.md
docs/api-reference.md
src/renderer.ts
src/rendertron.ts
src/test/app-test.ts
test-resources/include-date.html

Add possibility to pass timezone from [timezones list](https://source.chromium.org/chromium/chromium/deps/icu.git/+/faee8bc70570192d82d2978a71e2a615788597d1:source/data/misc/metaZones.txt) to `/render` and `/screenshot` endpoints

add timezone support

---

README.md
docs/configure.md
src/config.ts
src/renderer.ts
src/test/app-test.ts

Addresses #486 
Puppeteer returns null responses for page requests past the first one for some sites. The only reliable way to avoid this seems to be to disconnect from the browser and reconnect, the `createRender()` function on https://github.com/dwsmart/rendertron/blob/9bc42ddb6d3421152e9760b65cd8ffa752d71a82/src/rendertron.ts#L25 already reconnects with the required config if the browser disconnects, so calling `await this.browser.close();` after `await page.close();` fixes this issue, apparently with no massive performance hit.

Add this.browser.close() to force the browser to reconnect, fixes empty responses

---

.github/workflows/main.yml

Now we have multiple parallel jobs:
- Run the linter
- Run the integration tests
- Run the cache tests (this is the longest, for needing to download dependencies)
- Run the middleware tests
Also testing in multiple node versions: 10, 12 & 14.

Split tests in parallel jobs

---

README.md
src/config.ts
src/renderer.ts
src/test/app-test.ts
test-resources/restrict-test.test.html

This change adds request restriction based on a regex pattern. This pattern is specified in the config.
The following config would block the image requests.
```
{
"restrictedUrlPattern": ".*(\\.png|\\.jpg|\\.gif|\\.webp)($|\\?)"
}
```
Example usage for this feature would be to block image requests since in some use cases they do not provide additional value and use up the bandwidth.
Besides that. I might be general enough to cover domain blacklisting: #489

Added config specify url restriction pattern

---

src/filesystem-cache.ts
src/memory-cache.ts
src/test/app-test.ts
src/test/filesystem-cache-test.ts

Added URL 'sanitization' to remove `/render/` addressing #558 to memory cache
Moved logic to a function in both memory & filesystem cache
Also changed slightly to test if URL was prepended with `/render/` and only remove that.

sanitizes the cacheKey

---

src/test/app-test.ts

httpstat.us is flaky and we do have a local webserver to test http statuscode forwarding.

Removes httpstat.us from tests

---

package-lock.json
package.json
src/renderer.ts
tsconfig.json

This PR upgrades puppeteer to latest (10.0.0) version. As part of the fix following things were done:
1. Fixed renderer.ts for using puppeteer.HTTPRequest and puppeteer.HTTPResponse.
2. replaced deprecated page.addListener() with page.on()
3. tsconfig.json will now use skipLibCheck to avoid 'tsc' trying to pick/work on files in node_modules directory.

Upgrade puppeteer to latest (10.0.0)
